// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using MOVIE_API.Models.Enum;
using System;
using System.Collections.Generic;

namespace MOVIE_API.Models;

public partial class BookingDetail
{
    public int Id { get; set; }

    public int? IdMovie { get; set; }

    public BookingDetailState? State { get; set; }

    public DateTime? BookingDate { get; set; }

    public DateTime? ReturnDate { get; set; }

    public string Comment { get; set; }

    public int? IdBooking { get; set; }

    public virtual Booking IdBookingNavigation { get; set; }

    public virtual Movie IdMovieNavigation { get; set; }
}